# Generated by Django 5.0.4 on 2024-04-19 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ámbito de Acción',
                'verbose_name_plural': 'Ámbitos de Acción',
                'db_table': 'ent_ambitos_accion',
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cantón',
                'verbose_name_plural': 'Cantones',
                'db_table': 'ent_cantones',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Función',
                'verbose_name_plural': 'Tipos de Función',
                'db_table': 'ent_tipos_funcion',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'ent_provincias',
            },
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entidad',
                'verbose_name_plural': 'Tipos de Entidad',
                'db_table': 'ent_tipos_entidad',
            },
        ),
        migrations.CreateModel(
            name='TipoGad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de GAD',
                'verbose_name_plural': 'Tipo de GAD',
                'db_table': 'ent_tipos_gad',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Organización',
                'verbose_name_plural': 'Tipos de Organización',
                'db_table': 'ent_tipos_organizacion',
            },
        ),
        migrations.CreateModel(
            name='Zonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zonal',
                'verbose_name_plural': 'Zonales',
                'db_table': 'ent_zonales',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.canton')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'ent_parroquias',
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.provincia'),
        ),
    ]
