# Generated by Django 5.0.4 on 2024-04-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipogad',
            options={'verbose_name': 'Tipo de GAD', 'verbose_name_plural': 'Tipo de GAD'},
        ),
        migrations.AlterField(
            model_name='zonal',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
