# Generated by Django 5.0.4 on 2024-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='file_ordenanza',
            field=models.FileField(null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='file_registro_oficial',
            field=models.FileField(null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='file_ruc',
            field=models.FileField(null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='ruc',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono_responsable',
            field=models.CharField(max_length=10),
        ),
    ]
